#!/usr/bin/env bash
python /data/benchmark_metrics/insight/qwen_2511_attention_fullmap.py \
  --prompts_json /mnt/jfs/bench-bucket/sref_bench/sample_800_sref_200_content/prompts.json \
  --cref_dir /mnt/jfs/bench-bucket/sref_bench/sample_800_sref_200_content/cref \
  --sref_dir /mnt/jfs/bench-bucket/sref_bench/sample_800_sref_200_content/sref \
  --out_dir /data/benchmark_metrics/logs/qwen-edit-attn-fullmap \
  --model_name /mnt/jfs/model_zoo/qwen/Qwen-Image-Edit-2511/ \
  --gpus 0 \
  --key_txt /data/benchmark_metrics/insight/key.txt \
  --steps 28 \
  --true-cfg-scale 4.0 \
  --max-tokens 128 \
  --aggregate-head mean \
  --aggregate-block mean \
  --step-stride 4 \
  --block-stride 4 \
  --panel-size 1.1 \
  --image-dpi 240 \
  --ref-labels cref,sref \
  --attn-cmap turbo \
  --attn-gamma 0.48 \
  --high-attn-quantile 0.9 \
  --high-attn-contour-color "#00e5ff" \
  --high-attn-contour-width 1.0 \
  --boundary-linewidth 1.6 \
  --save-format png
